version: '3.8'

services:
  bot:
    build: .
    restart: unless-stopped
    volumes:
      - ./data:/app/data  # Монтируем папку с БД
      - ./logs:/app/logs  # Монтируем логи
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_PATH=/app/data/bot_database.db
    command: >
      sh -c "python /app/app/init_db.py && python /app/app/bot.py"
